inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
